services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: stock_portfolio
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-network

  springboot-app:
    build: ./StockProtfolioProject
    container_name: springboot-container
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stock_portfolio?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SERVER_PORT: 8081
    ports:
      - "8081:8080"
    networks:
      - springboot-network

  frontend:
    build: ./Frontend/stock-portfolio-frontend
    container_name: react-container
    environment:
      - PORT=8100
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "8100:3000"
    networks:
      - springboot-network
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  mysql-data:

networks:
  springboot-network: